---
- name: Check installed packages on servers
  hosts: all
  gather_facts: no

  tasks:
    - name: Gather package facts
      package_facts:
        manager: auto

    - name: Show installed packages
      debug:
        var: ansible_facts.packages
