---
- name: List installed packages on Ubuntu/Debian servers
  hosts: all
  gather_facts: no
  tasks:
    - name: Get list of installed packages
      command: dpkg -l
      register: installed_packages

    - name: Show installed packages
      debug:
        var: installed_packages.stdout_lines
