---
- name: Show manually installed packages on Ubuntu/Debian
  hosts: all
  gather_facts: no
  tasks:
    - name: Get manually installed packages
      command: apt-mark showmanual
      register: manual_packages

    - name: Display manually installed packages
      debug:
        var: manual_packages.stdout_lines
