- name: Install Python3 on Ubuntu 22+
  hosts: all
  become: yes
  vars:
    python_packages:
      - python3
      - python3-pip
      - python3-venv

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Python3 packages
      apt:
        name: "{{ python_packages }}"
        state: present

    - name: Verify Python3 installation
      command: python3 --version
      register: python_version

    - name: Show installed Python version
      debug:
        msg: "Installed Python version: {{ python_version.stdout }}"
