---
- name: Create user & SSH key without password (works on AWX)
  hosts: all
  become: yes
  vars:
    new_user: "developer"

  tasks:

    - name: Create user without password
      user:
        name: "{{ new_user }}"
        shell: /bin/bash
        create_home: yes
        password: "*"

    - name: Create .ssh directory
      file:
        path: "/home/{{ new_user }}/.ssh"
        state: directory
        owner: "{{ new_user }}"
        group: "{{ new_user }}"
        mode: "0700"

    - name: Generate SSH key pair on remote machine
      command: ssh-keygen -t rsa -b 4096 -f /home/{{ new_user }}/.ssh/id_rsa -N ""
      args:
        creates: "/home/{{ new_user }}/.ssh/id_rsa"
      become_user: "{{ new_user }}"

    - name: Read private key
      slurp:
        src: "/home/{{ new_user }}/.ssh/id_rsa"
      register: private_key

    - name: Read public key
      slurp:
        src: "/home/{{ new_user }}/.ssh/id_rsa.pub"
      register: public_key

    - name: Show SSH Private key
      debug:
        msg: "{{ private_key.content | b64decode }}"

    - name: Show SSH Public key
      debug:
        msg: "{{ public_key.content | b64decode }}"
