---
- name: Create user on Ubuntu 22+ without password
  hosts: all
  become: yes               # escalate to root
  become_user: root

  vars:
    new_user: deployuser    # change to desired username

  tasks:

    - name: Create new user without password
      user:
        name: "{{ new_user }}"
        shell: /bin/bash
        create_home: yes
        password_lock: yes   # disables password login
