---
- name: Create dynamic Linux user and generate PEM key
  hosts: all
  become: yes
  become_user: root

  vars:
    new_user: sddeveloper   # <--- Sirf yahan user change karna hai!

  tasks:
    - name: Ensure user exists
      user:
        name: "{{ new_user }}"
        shell: /bin/bash
        state: present
        create_home: yes

    - name: Create .ssh directory
      file:
        path: "/home/{{ new_user }}/.ssh"
        state: directory
        owner: "{{ new_user }}"
        group: "{{ new_user }}"
        mode: '0700'

    - name: Generate SSH keypair for user
      openssh_keypair:
        path: "/home/{{ new_user }}/.ssh/id_rsa"
        owner: "{{ new_user }}"
        group: "{{ new_user }}"
        mode: '0600'
        type: rsa
        size: 2048
      register: keypair

    - name: Add public key to authorized_keys
      copy:
        dest: "/home/{{ new_user }}/.ssh/authorized_keys"
        content: "{{ keypair.public_key }}"
        owner: "{{ new_user }}"
        group: "{{ new_user }}"
        mode: '0600'

    - name: Show PEM private key
      debug:
        msg: "{{ keypair.private_key }}"
