---
- name: Create user & SSH key as root (AWX safe)
  hosts: all
  become: yes
  become_user: root

  vars:
    new_user: "developer"
    ssh_dir: "/home/{{ new_user }}/.ssh"
    key_path: "/home/{{ new_user }}/.ssh/id_rsa"
ss
  tasks:

    - name: Create user without password
      user:
        name: "{{ new_user }}"
        shell: /bin/bash
        create_home: yes
        password: "*"

    - name: Create .ssh directory
      file:
        path: "{{ ssh_dir }}"
        state: directory
        owner: "{{ new_user }}"
        group: "{{ new_user }}"
        mode: "0700"

    - name: Generate SSH key pair as ROOT on behalf of user
      command: ssh-keygen -t rsa -b 4096 -f "{{ key_path }}" -N ""
      args:
        creates: "{{ key_path }}"

    - name: Set correct owner for key files
      file:
        path: "{{ item }}"
        owner: "{{ new_user }}"
        group: "{{ new_user }}"
        mode: "0600"
      loop:
        - "{{ key_path }}"
        - "{{ key_path }}.pub"

    - name: Read private key
      slurp:
        src: "{{ key_path }}"
      register: private_key

    - name: Read public key
      slurp:
        src: "{{ key_path }}.pub"
      register: public_key

    - name: Show PRIVATE KEY
      debug:
        msg: "{{ private_key.content | b64decode }}"

    - name: Show PUBLIC KEY
      debug:
        msg: "{{ public_key.content | b64decode }}"
