---
- name: Create Ubuntu user and generate SSH key
  hosts: all
  become: yes
  become_user: root

  tasks:
    - name: Ensure developer user exists
    - user:
        name: developer
        shell: /bin/bash
        state: present
        create_home: yes

    - name: Create .ssh directory
      file:
        path: /home/developer/.ssh
        state: directory
        owner: developer
        group: developer
        mode: '0700'

    - name: Generate SSH keypair for developer
      openssh_keypair:
        path: /home/developer/.ssh/id_rsa
        owner: developer
        group: developer
        mode: '0600'
        type: rsa
        size: 2048
      register: keypair

    - name: Add public key to authorized_keys
      copy:
        dest: /home/developer/.ssh/authorized_keys
        content: "{{ keypair.public_key }}"
        owner: developer
        group: developer
        mode: '0600'

    - name: Display private key (PEM)
      debug:
        msg: "{{ keypair.private_key }}"
